### ISSUE TITLE
adding database

### ISSUE THREAD

**Issue by Robitx** [Robitx/inceptus#1]
Having dilemma about choosing the "right" db. Will go with either PostgreSQL or 
ScyllaDB (or maybe both).

- [x] docker-compose orchestrating local db cluster
- [x] package wrapping interaction with db
- [x] server_template with example db usage

**Comment by tivvit** [comment]
There is no "right" DB. PostgreSQL interface is very convenient (used also in Cockroach). 

ScyllaDB (Cassandra) is suitable for storing billions of elements. 

Supporting both is a nice idea but the interface (some kind of wrapper) may cause a lot of problems

**Comment by Robitx** [comment]
@tivvit Hence the double quotes.. I will start with PostgreSQL since it has much wider adoption and use cases than ScyllaDB (I like it, but its a niche of a niche for heavy stuff).

Yes unification under common generic interface would be pointless (cutting off best parts of each database to get something common while crippling both), but I might still add support for both (with different wrappers) so I could choose based on the project at hand.

**Comment by Robitx** [comment]
Ok, I've finally found some time to add db package and implement trivial interaction with db inside server_template (just statically in code, not exposed by API routes).
