### ISSUE TITLE
adding load balancing proxy with https

### ISSUE THREAD

**Issue by Robitx** [Robitx/inceptus#2]
Nginx? Traefik? Caddy? Envoy? ..

**Comment by tivvit** [comment]
> Nginx? Traefik? Caddy? Envoy? ..

Just chose one - a community of the project will add others if they are going to need it. It is not tightly coupled to the project.

**Comment by Robitx** [comment]
@tivvit obviously, I'll add just one, but first need to overcome choice overload..

I know nginx, it's a safe choice, but also old + I hate the open source vs Nginx Plus model. I would use https://nginxproxymanager.com/

Zero experiences with the rest => learning opportunity.

Btw. https://github.com/NickMRamirez/Proxy-Benchmarks

Envoy is really fast, but configuration is hell. Traefik tires to be easy to use and is almost as fast as NGINX, but nginx can also be dumb down with nginx proxy manager.

I'll try to pass the Envoy's config hell..

**Comment by tivvit** [comment]
Knowing how to configure Envoy sounds like a good skill to have and the speed test are suggesting that it is a reasonable choice.

**Comment by Robitx** [comment]
Dev environment solved with Traefik 9922adf1d054d37cb965813ad0e07e5bbe6d0363
Prod setup will be different for everybody (I'll probably end up with https://cloud.google.com/load-balancing)
